steps:
  # Step 1: Export the database to a SQL file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud sql export sql \
          feisty-return-438307-f5:us-central1:d3v-5 \
          gs://demo-bucket-sql-dump/d3v-db-export.sql \
          --database=d3v-db \
          --quiet

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: "1200s"  # Set timeout for long-running operations
